language: go
install: go get github.com/spf13/hugo
before_script:
  - sudo apt-get update
  - sudo apt-get install nodejs
  - sudo npm install -g gulp
script:
  - hugo
  - npm install
  - gulp
  - bash ./deploy.sh
notifications:
    email:
        on_failure: always
branches:
  only:
  - master