language: go
go:
  - 1.10.x
install: go get -u github.com/gohugoio/hugo
before_script:
  - sudo apt-get update
  - sudo apt-get install nodejs npm
  - sudo npm set strict-ssl false
  - sudo npm install -g gulp
  - export GO111MODULE=on
  - go mod init
script:
  - npm install
  - gulp
  - hugo
  - gulp
  - bash ./deploy.sh
notifications:
    email:
        on_failure: always
branches:
  only:
  - master